package Metodo;
/*se importan las librerias que se van a usar en esta ventana */

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Listapersonas extends javax.swing.JFrame {

    //se crea una matriz que va almacenar los elementos del array para luego pasarlos a la tabla
    Object[][] pers;
    Ventana ventanaPrincipal;

    /* se inicializan los componentes del formulario de personas*/
    public Listapersonas() {
        initComponents();
    }
    /* este es el contructor del formulario*/

    public Listapersonas(Persona[] pers, Ventana ventana) {
        ventanaPrincipal = ventana;
        initComponents();
        ajustarDatos(pers);
        llenarTabla();
    }

    /*aqui se define el nombre de las columnas 
     luego se crea la tabla y se asigna las columnas junto a la matriz como parametros*/
    private void llenarTabla() {
        String[] columnas = new String[]{
            "Tipo documentos", "Num de documeto", "Nombre", "Apellido", " Email ", "N° Celular ", " Fecha De Nacimiento "
        };
        DefaultTableModel dtm = new DefaultTableModel(pers, columnas);
        tbPersonas.setModel(dtm);
    }
    /* aqui se convierte el array en una matriz y se le asignan los atributos de los objetos en la fila 
     y la columna a la que corresponden de tal manera que la tabla quede organizada*/

    private void ajustarDatos(Persona[] personas) {
        pers = new Object[personas.length][7];
        for (int i = 0; i < personas.length; i++) {
            System.out.println("pers: " + personas[i]);
            pers[i][0] = personas[i].tipodoc;
            pers[i][1] = personas[i].ndoc;
            pers[i][2] = personas[i].noms;
            pers[i][3] = personas[i].apells;
            pers[i][4] = personas[i].email;
            pers[i][5] = personas[i].ncel;
            pers[i][6] = personas[i].fnaci;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPersonas = new javax.swing.JTable();
        Buttonagregarelemento = new javax.swing.JButton();
        EliminarButton = new javax.swing.JButton();
        ButtonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista De Personas"));

        tbPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo documentos", "N° de documeto", "Nombre", "Apellido", "Email", "N° Celular", "Fecha De Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(tbPersonas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        Buttonagregarelemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        Buttonagregarelemento.setText("Agregar");
        Buttonagregarelemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonagregarelementoActionPerformed(evt);
            }
        });

        EliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pencil_delete.png"))); // NOI18N
        EliminarButton.setText("Eliminar");
        EliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarButtonActionPerformed(evt);
            }
        });

        ButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/group_go.png"))); // NOI18N
        ButtonModificar.setText("Modificar");
        ButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Buttonagregarelemento)
                .addGap(18, 18, 18)
                .addComponent(EliminarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonModificar)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttonagregarelemento)
                    .addComponent(EliminarButton)
                    .addComponent(ButtonModificar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(920, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonagregarelementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonagregarelementoActionPerformed
        /* se hace esta funcion para que cree un nuevo campo de texto vacio para poder agregar una nueva persona*/
        ((DefaultTableModel) tbPersonas.getModel()).addRow(new Object[]{null, null, null, null, null, null, null});
    }//GEN-LAST:event_ButtonagregarelementoActionPerformed

    private void EliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarButtonActionPerformed
        /* se hace esto para poder eliminar la fila seleccionada en la tabla*/
        int fila = tbPersonas.getSelectedRow();
        if (fila >= 0) {
            ((DefaultTableModel) tbPersonas.getModel()).removeRow(tbPersonas.getSelectedRow());
        }
    }//GEN-LAST:event_EliminarButtonActionPerformed

    private void ButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarActionPerformed
        /* aqui se selecciona la tabla y se almacena en la variable que guarda ene el array que posteriomente
         se guarda en el archivo de texto*/
        int count = ((DefaultTableModel) tbPersonas.getModel()).getRowCount();
        ventanaPrincipal.pers = new Persona[count];
        for (int i = 0; i < count; i++) {
            Persona perTmp = new Persona();
            perTmp.tipodoc = "" + ((DefaultTableModel) tbPersonas.getModel()).getValueAt(i, 0);
            perTmp.ndoc = "" + ((DefaultTableModel) tbPersonas.getModel()).getValueAt(i, 1);
            perTmp.noms = "" + ((DefaultTableModel) tbPersonas.getModel()).getValueAt(i, 2);
            perTmp.apells = "" + ((DefaultTableModel) tbPersonas.getModel()).getValueAt(i, 3);
            perTmp.email = "" + ((DefaultTableModel) tbPersonas.getModel()).getValueAt(i, 4);
            perTmp.ncel = "" + ((DefaultTableModel) tbPersonas.getModel()).getValueAt(i, 5);
            perTmp.fnaci = "" + ((DefaultTableModel) tbPersonas.getModel()).getValueAt(i, 6);

            ventanaPrincipal.pers[i] = perTmp;
        }
        setVisible(false);
    }//GEN-LAST:event_ButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listapersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listapersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listapersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listapersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listapersonas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonModificar;
    private javax.swing.JButton Buttonagregarelemento;
    private javax.swing.JButton EliminarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPersonas;
    // End of variables declaration//GEN-END:variables
}
